### ISSUE TITLE
I had to run autogen.sh twice

### ISSUE THREAD

**Issue by joonazan** [remacs/remacs#1549] opened 2019-11-03 21:53 UTC
On the first run it installed a compiler and on the second run it made the configure file. This is not how the README says it works.

**Comment by shaleh** [comment] 2019-11-05 01:57
That is definitely odd. Can you tell us more about your system?

**Comment by joonazan** [comment] 2019-11-07 15:15
That was on a somewhat outdated Ubuntu on a Chromebook. I was not able to reproduce on my desktop Arch Linux.

**Comment by shaleh** [comment] 2019-11-07 20:43
Thank you for the update. I am inclined to close this if we cannot reproduce it. The autogen.sh script is made for us by the autotools suite. The only fix I can think of would be to better define a dependency inside configure.ac. But we would need to know which dependency needs help.

**Comment by cnasc** [comment] 2019-12-21 03:29
I just had the same thing happen to me. System details:
```
x86_64 Linux 5.3.15-138.current
AMD Ryzen 5 2400G with Radeon Vega Graphics @ 8x 3.6GHz
```

One key piece is that I am working from inside the docker image, not sure if @joonazan did the same.

Here's my actual session:
```
~/code/remacs $ sudo docker-compose exec remacs ./autogen.sh
Checking Rust toolchain install ...
info: syncing channel updates for 'nightly-2019-07-18-x86_64-unknown-linux-gnu'
info: latest update on 2019-07-18, rust version 1.38.0-nightly (bc2e84ca0 2019-07-17)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
Remacs currently requires Rust toolchain version nightly-2019-07-18.
```

I thought that at this point I would be good to run `configure`, but:

```
~/code/remacs $ sudo docker-compose exec remacs ./configure --enable-rust-debug
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"./configure\": stat ./configure: no such file or directory": unknown
```

After verifying that the file actually didn't exist, I tried running `autogen` again and got the following:

```
~/code/remacs $ sudo docker-compose exec remacs ./autogen.sh
Checking Rust toolchain install ...
Your system has the required Rust toolchain installed for building Remacs.
Checking whether you have the necessary tools...
(Read INSTALL.REPO for more details on building Remacs)
Checking for autoconf (need at least version 2.65) ... ok
Your system has the required tools.
Building aclocal.m4 ...
Running 'autoreconf -fi -I m4' ...
You can now run './configure'.
```

**Comment by shaleh** [comment] 2020-01-06 17:43
Which docker image did not work for you @cnasc ?

**Comment by cnasc** [comment] 2020-01-06 18:33
No worries @shaleh! Aside from installing and running docker, the console output above is exactly what I did so I think the docker image is just whatever `remacs-build:latest` was at the time I ran it.

As near as I can guess, the part of autoconf that checks for the Rust toolchain exits early right after doing the installation with `rustup`. Let me know if there are any other steps I can try that would be helpful.

**Comment by shaleh** [comment] 2020-01-06 19:16
Sorry, I meant, which Dockerfile are you using?

**Comment by cnasc** [comment] 2020-01-06 19:56
IIRC it was [this one](https://github.com/remacs/remacs/blob/master/docker/ubuntu/Dockerfile) but I will double check when I'm back on my desktop

**Comment by shaleh** [comment] 2020-01-06 22:22
@cnasc see #1560

**Comment by cnasc** [comment] 2020-01-06 22:54
Nice! I'll give that a test when I can

**Comment by shaleh** [comment] 2020-01-09 19:03
The Dockerfile is supposed to end up with the most current value from the rust-toolchain file. If yours is out of date though this bug will happen. The PR change makes it so autogen.sh will gracefully fail and tell you what to do. Then you can re-run autogen.sh.

**Closed** 2020-01-13 23:58 UTC
